inherit_gem:
  rubocop-shopify: rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  Exclude:
    - tmp/**/*
    - node_modules/**/*
    - coverage/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
